version: '3.1'

services:

  db:
    container_name: mysql-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./resources/init.sql:/docker-entrypoint-initdb.d/init.sql
      working_dir: /docker-entrypoint-initdb.d
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080